apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-4jkg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-4jkg@sha256:33baf27356ba6ad334808d5446bd83178ff6d7f3754b52ecc9ac3a3f40f18784
        name: my-nodejs
        resources: {}
status: {}
